name: 🔍 Other Issue
description: Report any other type of issue
title: "[OTHER] "
labels: ["misc"]
assignees: []
body:
  - type: checkboxes
    attributes:
      label: Issue Type Verification
      description: Please confirm this issue doesn't fit into other categories
      options:
        - label: I confirm this is not a bug report or feature request
          required: true
        - label: I have searched for similar issues
          required: true

  - type: dropdown
    attributes:
      label: Issue Category
      description: What type of issue is this?
      options:
        - Documentation
        - Performance
        - Security
        - Question
        - Other
    validations:
      required: true

  - type: textarea
    attributes:
      label: Issue Description
      description: Please provide a clear and concise description of the issue
      placeholder: Describe what you'd like to discuss or report...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Add any other context, screenshots, or relevant information about the issue here.
        
        Tip: You can attach images or files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
