name: Common Setup

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        default: "3.13"
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      venv-path: ${{ steps.get-env.outputs.venv-path }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.0.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache Poetry virtual environment
        id: cache-poetry
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-python-${{ inputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        id: install-deps
        run: |
          if [ "${{ steps.cache-poetry.outputs.cache-hit }}" != "true" ]; then
            poetry install
          fi

      - name: Get virtual environment path
        id: get-env
        run: echo "venv-path=$(poetry env info --path)" >> $GITHUB_OUTPUT