name: CI 

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: ${{ !contains(github.ref, 'main')}}

jobs:
  Lint:
    strategy:
      matrix:
        python-version: [ "3.11", "3.12", "3.13" ]
    uses: ./.github/workflows/base.yml
    with:
      python-version: ${{ matrix.python-version }}
    steps:
      - name: Lint source code
        run: make lint

  Unit-Test:
    needs:
      - Lint
    strategy:
      matrix:
        python-version: [ "3.11", "3.12", "3.13" ]
    uses: ./.github/workflows/base.yml
    with:
      python-version: ${{ matrix.python-version }}
    steps:
      - name: Run tests
        run: make test-ci

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.1.2
        with:
          flags: main
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: axioma-ai-labs/nevron
